// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Ability } from "./tables/Ability.sol";
import { AbilityChat, AbilityChatTableId } from "./tables/AbilityChat.sol";
import { AbilityConsume, AbilityConsumeTableId } from "./tables/AbilityConsume.sol";
import { AbilityMove, AbilityMoveTableId } from "./tables/AbilityMove.sol";
import { AbilityPlay, AbilityPlayTableId } from "./tables/AbilityPlay.sol";
import { CarriedBy, CarriedByTableId } from "./tables/CarriedBy.sol";
import { CarryingCapacity, CarryingCapacityTableId } from "./tables/CarryingCapacity.sol";
import { Commit, CommitTableId } from "./tables/Commit.sol";
import { Core, CoreTableId } from "./tables/Core.sol";
import { CreationBlock, CreationBlockTableId } from "./tables/CreationBlock.sol";
import { Energy, EnergyTableId } from "./tables/Energy.sol";
import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { Goal, GoalTableId } from "./tables/Goal.sol";
import { Loot, LootTableId } from "./tables/Loot.sol";
import { Matter, MatterTableId } from "./tables/Matter.sol";
import { Point, PointTableId } from "./tables/Point.sol";
import { Portable, PortableTableId } from "./tables/Portable.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { ReadyBlock, ReadyBlockTableId } from "./tables/ReadyBlock.sol";
import { Untraversable, UntraversableTableId } from "./tables/Untraversable.sol";
