// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Core, CoreTableId } from "./tables/Core.sol";
import { Energy, EnergyTableId } from "./tables/Energy.sol";
import { Points, PointsTableId } from "./tables/Points.sol";
import { ReadyBlock, ReadyBlockTableId } from "./tables/ReadyBlock.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
