// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IConsumeSystem {
  function moving_castles_ConsumeSystem_consume(bytes32 _consumableEntity) external;
}
