// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICountSystem {
  function moving_castles_CountSystem_init() external;

  function moving_castles_CountSystem_count(uint32 _val) external;
}
