// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IDropSystem {
  function moving_castles_DropSystem_drop(bytes32 _portableEntity) external;
}
