// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IJoinSystem {
  function moving_castles_JoinSystem_join(uint32 _bodyIndex) external;
}
