// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMatchSystem {
  function moving_castles_MatchSystem_init() external;

  function moving_castles_MatchSystem_start() external;

  function moving_castles_MatchSystem_end() external;
}
