// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSystem {
  function moving_castles_MoveSystem_move(int32 x, int32 y) external;
}
