// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IOpenSystem {
  function moving_castles_OpenSystem_open(bytes32 _lootEntity) external;
}
