// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPickUpSystem {
  function moving_castles_PickUpSystem_pickUp(bytes32 _portableEntity) external;
}
