// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITransferSystem {
  function moving_castles_TransferSystem_transfer(bytes32 _portableEntity, bytes32 _targetBaseEntity) external;
}
