// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITravelSystem {
  function moving_castles_TravelSystem_travel(uint256 realmId) external;
}
