// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IStore } from "@latticexyz/store/src/IStore.sol";

import { IWorldCore } from "@latticexyz/world/src/interfaces/IWorldCore.sol";

import { IConsumeSystem } from "./IConsumeSystem.sol";
import { IDevSystem } from "./IDevSystem.sol";
import { IDropSystem } from "./IDropSystem.sol";
import { IHarvestSystem } from "./IHarvestSystem.sol";
import { IInitSystem } from "./IInitSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { IOpenSystem } from "./IOpenSystem.sol";
import { IPickUpSystem } from "./IPickUpSystem.sol";
import { IPlaySystem } from "./IPlaySystem.sol";
import { ISpawnSystem } from "./ISpawnSystem.sol";
import { ITransferSystem } from "./ITransferSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IStore,
  IWorldCore,
  IConsumeSystem,
  IDevSystem,
  IDropSystem,
  IHarvestSystem,
  IInitSystem,
  IMoveSystem,
  IOpenSystem,
  IPickUpSystem,
  IPlaySystem,
  ISpawnSystem,
  ITransferSystem
{

}
